#server:
#  port: 8080
##
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/robot-game?serverTimezone=UTC
#    username: root
#    password: test1234
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    database: MYSQL
#    show-sql: true
#    generate-ddl: true
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        show_sql: false
#        format_sql: false
#        dialect: org.hibernate.dialect.MySQL8Dialect
#

server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: test1234
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      generate-ddl: true
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
