#server:
#  port: 8080
##
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/robot-game?serverTimezone=UTC
#    username: root
#    password: test1234
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    database: MYSQL
#    show-sql: true
#    generate-ddl: true
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        show_sql: false
#        format_sql: false
#        dialect: org.hibernate.dialect.MySQL8Dialect
#
#cors-policies: http://localhost:4200, http://127.0.0.1:4200

#  server.port=8080
#
#  spring.datasource.url=jdbc:postgresql://localhost:5432/movies
#  spring.datasource.username=root
#  spring.datasource.password=test1234
#  spring.datasource.driver-class-name=org.postgresql.Driver
#
#  spring.jpa.database=POSTGRESQL
#  spring.jpa.show-sql=true
#  spring.jpa.generate-ddl=true
#  spring.jpa.hibernate.ddl-auto=update
#  spring.jpa.properties.hibernate.show_sql=false
#  spring.jpa.properties.hibernate.format_sql=false
#  spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#
#  cors-policies=http://localhost:4200,http://127.0.0.1:4200

server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: test1234
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      generate-ddl: true
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
